---
title: "Reproducible Research: Peer Assessment 1"
author: "Luis Hernandez"
date: "11/16/2019"
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data
```{r, warning=FALSE,message=FALSE}
# load libraries
library(readr)
library(ggplot2)
library(imputeTS)
library(dplyr)
# unzip and load
unzip("activity.zip")
activity_data <- read_csv("activity.csv", col_types = cols(date = col_date(format = "%Y-%m-%d")))
```

## What is mean total number of steps taken per day?
```{r}
total_steps_by_date <- aggregate(steps ~ date,activity_data, sum, na.rm = TRUE)
mean_steps_by_date <- aggregate(steps ~ date,activity_data, mean, na.rm = TRUE)
mean(total_steps_by_date$steps)
median(total_steps_by_date$steps)
```

```{r, echo=FALSE}
ggplot(data = total_steps_by_date, aes(x = date, y = steps)) + geom_point(color= 'red') + 
  geom_line(color= 'red') +
  ggtitle('Total Steps by Day')

## Plot of histogram of the total number of steps taken each day
hist(as.ts(total_steps_by_date$steps), xlab="Total number of steps", ylab="Number of Days", breaks = nrow(total_steps_by_date),
     main="Histogram of Total Number of Steps by Number of Days", col='skyblue3')

# ggplot() + geom_violin(data = total_steps_by_date, aes(x = date, y = steps), color= 'red') +
#   ggtitle('Violin Plot of Total Steps by Day') + 
#   theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title = element_blank())

ggplot(data = mean_steps_by_date, aes(x = date, y = steps)) + geom_point(color= 'red') + 
  geom_line(color= 'red') +
  ggtitle('Mean Steps by Day')

# ggplot() + geom_violin(data = mean_steps_by_date, aes(x = date, y = steps), color= 'red') +
#   ggtitle('Violin Plot of Mean Steps by Day') + 
#   theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title = element_blank())
```


## What is the average daily activity pattern?
```{r}
# Calculate mean steps per interval and omit NAs
average_daily_activity_pattern <- aggregate(steps ~ interval,activity_data, mean, na.rm = TRUE)
```

```{r, echo=FALSE}
ggplot() + geom_line(data = average_daily_activity_pattern, aes(x = interval, y = steps), color= 'red') +
  theme_grey() +  
  labs(x = "interval", y = "Number of steps", title = "Average Daily Activity Pattern")
```


## Imputing missing values
```{r}
# I use the imputeTS library to analyze and impute values based on moving avergae values
# display missing value stats
statsNA(activity_data$steps)
# use moving average to impute
imputed_steps <- na_ma(activity_data$steps, k = 4, weighting = "exponential", maxgap = Inf)
# replace missing values
activity_data_imputed <- activity_data %>% mutate(steps  = ifelse(is.na(steps), imputed_steps[1], steps))
```

```{r, echo=FALSE}
# plot distribution of NA
plotNA.distributionBar(activity_data$steps)
# plot of activity with imputed data
ggplot() + geom_line(data = activity_data_imputed, aes(x = interval, y = steps), color= 'red') +
  theme_grey() +  
  labs(x = "interval", y = "Number of steps", title = "Average Daily Activity Pattern (with imputed data)")
```

```{r, echo=FALSE}
## Plot of histogram of the total number of steps taken each day after imputing
total_steps_by_date_imputed <- aggregate(steps ~ date,activity_data_imputed, sum, na.rm = TRUE)

hist(as.ts(total_steps_by_date_imputed$steps), xlab="Total number of steps", ylab="Number of Days", breaks = nrow(total_steps_by_date),
     main="Histogram of Total Number of Steps by Number of Days (imputed)", col='skyblue3')
```

## Are there differences in activity patterns between weekdays and weekends?

```{r}
# use daily activity with imputed data, create indicator for weekend days and subset data 
activity_data_imputed <- mutate(activity_data_imputed, day = weekdays(activity_data_imputed$date))
weekend_days <- c('Saturday', 'Sunday')
activity_data_imputed$weekend <- factor((weekdays(activity_data_imputed$date) %in% weekend_days), levels=c(TRUE, FALSE))

weekdays <- subset(activity_data_imputed, weekend == FALSE)
weekends <- subset(activity_data_imputed, weekend == TRUE)
```



```{r, echo=FALSE}
# plot weekdays activity pattern
average_weekday_activity_pattern <- aggregate(steps ~ interval,weekdays, mean, na.rm = TRUE)
ggplot() + geom_line(data = average_weekday_activity_pattern, aes(x = interval, y = steps), color= 'red') +
  theme_grey() +  
  ylim(0,220) +
  labs(x = "interval", y = "Number of steps", title = "Average Weekday Activity Pattern")

# plot weekend activity pattern
average_weekend_activity_pattern <- aggregate(steps ~ interval,weekends, mean, na.rm = TRUE)
ggplot() + geom_line(data = average_weekend_activity_pattern, aes(x = interval, y = steps), color= 'red') +
  theme_grey() +  
  ylim(0,220) +
  labs(x = "interval", y = "Number of steps", title = "Average Weekend Activity Pattern")

```

